/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AchatsRouteImport } from './routes/achats'
import { Route as AlertesRouteImport } from './routes/alertes'
import { Route as CommunityRouteImport } from './routes/community'
import { Route as ConfigurationRouteImport } from './routes/configuration'
import { Route as FinanceRouteImport } from './routes/finance'
import { Route as LoginRouteImport } from './routes/login'
import { Route as ProductionRouteImport } from './routes/production'
import { Route as SatisfactionRouteImport } from './routes/satisfaction'
import { Route as AlerteAlertIdRouteImport } from './routes/alerte.$alertId'
import { Route as AnalyseAnalysisIdRouteImport } from './routes/analyse.$analysisId'
import { Route as FeedbackFeedbackIdRouteImport } from './routes/feedback.$feedbackId'
import { Route as FournisseurSupplierIdRouteImport } from './routes/fournisseur.$supplierId'
import { Route as PlatDishIdRouteImport } from './routes/plat.$dishId'
import { Route as ProblemeIssueIdRouteImport } from './routes/probleme.$issueId'
import { Route as ProduitMaterialIdRouteImport } from './routes/produit.$materialId'
import { Route as RecommandationRecoIdRouteImport } from './routes/recommandation.$recoId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AchatsRoute = AchatsRouteImport.update({
  id: '/achats',
  path: '/achats',
  getParentRoute: () => rootRouteImport,
} as any)
const AlertesRoute = AlertesRouteImport.update({
  id: '/alertes',
  path: '/alertes',
  getParentRoute: () => rootRouteImport,
} as any)
const CommunityRoute = CommunityRouteImport.update({
  id: '/community',
  path: '/community',
  getParentRoute: () => rootRouteImport,
} as any)
const ConfigurationRoute = ConfigurationRouteImport.update({
  id: '/configuration',
  path: '/configuration',
  getParentRoute: () => rootRouteImport,
} as any)
const FinanceRoute = FinanceRouteImport.update({
  id: '/finance',
  path: '/finance',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductionRoute = ProductionRouteImport.update({
  id: '/production',
  path: '/production',
  getParentRoute: () => rootRouteImport,
} as any)
const SatisfactionRoute = SatisfactionRouteImport.update({
  id: '/satisfaction',
  path: '/satisfaction',
  getParentRoute: () => rootRouteImport,
} as any)
const AlerteAlertIdRoute = AlerteAlertIdRouteImport.update({
  id: '/alerte/$alertId',
  path: '/alerte/$alertId',
  getParentRoute: () => rootRouteImport,
} as any)
const AnalyseAnalysisIdRoute = AnalyseAnalysisIdRouteImport.update({
  id: '/analyse/$analysisId',
  path: '/analyse/$analysisId',
  getParentRoute: () => rootRouteImport,
} as any)
const FeedbackFeedbackIdRoute = FeedbackFeedbackIdRouteImport.update({
  id: '/feedback/$feedbackId',
  path: '/feedback/$feedbackId',
  getParentRoute: () => rootRouteImport,
} as any)
const FournisseurSupplierIdRoute = FournisseurSupplierIdRouteImport.update({
  id: '/fournisseur/$supplierId',
  path: '/fournisseur/$supplierId',
  getParentRoute: () => rootRouteImport,
} as any)
const PlatDishIdRoute = PlatDishIdRouteImport.update({
  id: '/plat/$dishId',
  path: '/plat/$dishId',
  getParentRoute: () => rootRouteImport,
} as any)
const ProblemeIssueIdRoute = ProblemeIssueIdRouteImport.update({
  id: '/probleme/$issueId',
  path: '/probleme/$issueId',
  getParentRoute: () => rootRouteImport,
} as any)
const ProduitMaterialIdRoute = ProduitMaterialIdRouteImport.update({
  id: '/produit/$materialId',
  path: '/produit/$materialId',
  getParentRoute: () => rootRouteImport,
} as any)
const RecommandationRecoIdRoute = RecommandationRecoIdRouteImport.update({
  id: '/recommandation/$recoId',
  path: '/recommandation/$recoId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/achats': typeof AchatsRoute
  '/alertes': typeof AlertesRoute
  '/community': typeof CommunityRoute
  '/configuration': typeof ConfigurationRoute
  '/finance': typeof FinanceRoute
  '/login': typeof LoginRoute
  '/production': typeof ProductionRoute
  '/satisfaction': typeof SatisfactionRoute
  '/alerte/$alertId': typeof AlerteAlertIdRoute
  '/analyse/$analysisId': typeof AnalyseAnalysisIdRoute
  '/feedback/$feedbackId': typeof FeedbackFeedbackIdRoute
  '/fournisseur/$supplierId': typeof FournisseurSupplierIdRoute
  '/plat/$dishId': typeof PlatDishIdRoute
  '/probleme/$issueId': typeof ProblemeIssueIdRoute
  '/produit/$materialId': typeof ProduitMaterialIdRoute
  '/recommandation/$recoId': typeof RecommandationRecoIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/achats': typeof AchatsRoute
  '/alertes': typeof AlertesRoute
  '/community': typeof CommunityRoute
  '/configuration': typeof ConfigurationRoute
  '/finance': typeof FinanceRoute
  '/login': typeof LoginRoute
  '/production': typeof ProductionRoute
  '/satisfaction': typeof SatisfactionRoute
  '/alerte/$alertId': typeof AlerteAlertIdRoute
  '/analyse/$analysisId': typeof AnalyseAnalysisIdRoute
  '/feedback/$feedbackId': typeof FeedbackFeedbackIdRoute
  '/fournisseur/$supplierId': typeof FournisseurSupplierIdRoute
  '/plat/$dishId': typeof PlatDishIdRoute
  '/probleme/$issueId': typeof ProblemeIssueIdRoute
  '/produit/$materialId': typeof ProduitMaterialIdRoute
  '/recommandation/$recoId': typeof RecommandationRecoIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/achats': typeof AchatsRoute
  '/alertes': typeof AlertesRoute
  '/community': typeof CommunityRoute
  '/configuration': typeof ConfigurationRoute
  '/finance': typeof FinanceRoute
  '/login': typeof LoginRoute
  '/production': typeof ProductionRoute
  '/satisfaction': typeof SatisfactionRoute
  '/alerte/$alertId': typeof AlerteAlertIdRoute
  '/analyse/$analysisId': typeof AnalyseAnalysisIdRoute
  '/feedback/$feedbackId': typeof FeedbackFeedbackIdRoute
  '/fournisseur/$supplierId': typeof FournisseurSupplierIdRoute
  '/plat/$dishId': typeof PlatDishIdRoute
  '/probleme/$issueId': typeof ProblemeIssueIdRoute
  '/produit/$materialId': typeof ProduitMaterialIdRoute
  '/recommandation/$recoId': typeof RecommandationRecoIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/achats'
    | '/alertes'
    | '/community'
    | '/configuration'
    | '/finance'
    | '/login'
    | '/production'
    | '/satisfaction'
    | '/alerte/$alertId'
    | '/analyse/$analysisId'
    | '/feedback/$feedbackId'
    | '/fournisseur/$supplierId'
    | '/plat/$dishId'
    | '/probleme/$issueId'
    | '/produit/$materialId'
    | '/recommandation/$recoId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/achats'
    | '/alertes'
    | '/community'
    | '/configuration'
    | '/finance'
    | '/login'
    | '/production'
    | '/satisfaction'
    | '/alerte/$alertId'
    | '/analyse/$analysisId'
    | '/feedback/$feedbackId'
    | '/fournisseur/$supplierId'
    | '/plat/$dishId'
    | '/probleme/$issueId'
    | '/produit/$materialId'
    | '/recommandation/$recoId'
  id:
    | '__root__'
    | '/'
    | '/achats'
    | '/alertes'
    | '/community'
    | '/configuration'
    | '/finance'
    | '/login'
    | '/production'
    | '/satisfaction'
    | '/alerte/$alertId'
    | '/analyse/$analysisId'
    | '/feedback/$feedbackId'
    | '/fournisseur/$supplierId'
    | '/plat/$dishId'
    | '/probleme/$issueId'
    | '/produit/$materialId'
    | '/recommandation/$recoId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AchatsRoute: typeof AchatsRoute
  AlertesRoute: typeof AlertesRoute
  CommunityRoute: typeof CommunityRoute
  ConfigurationRoute: typeof ConfigurationRoute
  FinanceRoute: typeof FinanceRoute
  LoginRoute: typeof LoginRoute
  ProductionRoute: typeof ProductionRoute
  SatisfactionRoute: typeof SatisfactionRoute
  AlerteAlertIdRoute: typeof AlerteAlertIdRoute
  AnalyseAnalysisIdRoute: typeof AnalyseAnalysisIdRoute
  FeedbackFeedbackIdRoute: typeof FeedbackFeedbackIdRoute
  FournisseurSupplierIdRoute: typeof FournisseurSupplierIdRoute
  PlatDishIdRoute: typeof PlatDishIdRoute
  ProblemeIssueIdRoute: typeof ProblemeIssueIdRoute
  ProduitMaterialIdRoute: typeof ProduitMaterialIdRoute
  RecommandationRecoIdRoute: typeof RecommandationRecoIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/achats': {
      id: '/achats'
      path: '/achats'
      fullPath: '/achats'
      preLoaderRoute: typeof AchatsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/alertes': {
      id: '/alertes'
      path: '/alertes'
      fullPath: '/alertes'
      preLoaderRoute: typeof AlertesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/community': {
      id: '/community'
      path: '/community'
      fullPath: '/community'
      preLoaderRoute: typeof CommunityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/configuration': {
      id: '/configuration'
      path: '/configuration'
      fullPath: '/configuration'
      preLoaderRoute: typeof ConfigurationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/finance': {
      id: '/finance'
      path: '/finance'
      fullPath: '/finance'
      preLoaderRoute: typeof FinanceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/production': {
      id: '/production'
      path: '/production'
      fullPath: '/production'
      preLoaderRoute: typeof ProductionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/satisfaction': {
      id: '/satisfaction'
      path: '/satisfaction'
      fullPath: '/satisfaction'
      preLoaderRoute: typeof SatisfactionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/alerte/$alertId': {
      id: '/alerte/$alertId'
      path: '/alerte/$alertId'
      fullPath: '/alerte/$alertId'
      preLoaderRoute: typeof AlerteAlertIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/analyse/$analysisId': {
      id: '/analyse/$analysisId'
      path: '/analyse/$analysisId'
      fullPath: '/analyse/$analysisId'
      preLoaderRoute: typeof AnalyseAnalysisIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/feedback/$feedbackId': {
      id: '/feedback/$feedbackId'
      path: '/feedback/$feedbackId'
      fullPath: '/feedback/$feedbackId'
      preLoaderRoute: typeof FeedbackFeedbackIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/fournisseur/$supplierId': {
      id: '/fournisseur/$supplierId'
      path: '/fournisseur/$supplierId'
      fullPath: '/fournisseur/$supplierId'
      preLoaderRoute: typeof FournisseurSupplierIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/plat/$dishId': {
      id: '/plat/$dishId'
      path: '/plat/$dishId'
      fullPath: '/plat/$dishId'
      preLoaderRoute: typeof PlatDishIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/probleme/$issueId': {
      id: '/probleme/$issueId'
      path: '/probleme/$issueId'
      fullPath: '/probleme/$issueId'
      preLoaderRoute: typeof ProblemeIssueIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/produit/$materialId': {
      id: '/produit/$materialId'
      path: '/produit/$materialId'
      fullPath: '/produit/$materialId'
      preLoaderRoute: typeof ProduitMaterialIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/recommandation/$recoId': {
      id: '/recommandation/$recoId'
      path: '/recommandation/$recoId'
      fullPath: '/recommandation/$recoId'
      preLoaderRoute: typeof RecommandationRecoIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AchatsRoute: AchatsRoute,
  AlertesRoute: AlertesRoute,
  CommunityRoute: CommunityRoute,
  ConfigurationRoute: ConfigurationRoute,
  FinanceRoute: FinanceRoute,
  LoginRoute: LoginRoute,
  ProductionRoute: ProductionRoute,
  SatisfactionRoute: SatisfactionRoute,
  AlerteAlertIdRoute: AlerteAlertIdRoute,
  AnalyseAnalysisIdRoute: AnalyseAnalysisIdRoute,
  FeedbackFeedbackIdRoute: FeedbackFeedbackIdRoute,
  FournisseurSupplierIdRoute: FournisseurSupplierIdRoute,
  PlatDishIdRoute: PlatDishIdRoute,
  ProblemeIssueIdRoute: ProblemeIssueIdRoute,
  ProduitMaterialIdRoute: ProduitMaterialIdRoute,
  RecommandationRecoIdRoute: RecommandationRecoIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
